export const GAME_WIDTH = 430;
export const GAME_HEIGHT = 932;
export const WORLD_WIDTH = 5000;
export const WORLD_HEIGHT = GAME_HEIGHT;
export const GROUND_HEIGHT = 290;
export const DYNAMIC_GROUND = window.innerHeight * 30/100; //30% dari total layar
export const PLAYER_Y = GAME_HEIGHT - DYNAMIC_GROUND - 35;
export const PLAYER_RADIUS = 18;
export const CONTROL_POS = DYNAMIC_GROUND * 15/100; //ubah ditengah2 ground
// export const CONTROL_HEIGHT = 100;
export const ANIMATION_SPEED = 100;